# business, tech, finance
att_news_finance <- c(
  "Yahoo! Finance USA",
  "Forbes",
  "Business Insider",
  "Finanz Nachrichten",
  "World Economic Forum",
  "MarketScreener",
  "Ticker Tech",
  "Business Standard",
  "Global Advisors",
  "Business Insider Australia ",
  "Business Insider India",
  "Tech Times",
  "International Business Times",
  "Daily Journal",
  "NRC Handelsblad",
  "Ariva",
  "ProfitQuotes.com",
  "Business Insider Singapore",
  "Finanzen.ch",
  "Seeking Alpha",
  "Eco Business",
  "Business Insider Nederland",
  "Fast Company",
  "Business Insider Malaysia",
  "NASDAQ",
  "VB Profiles",
  "EconoTimes",
  "Stockwatch",
  "Business Insider UK",
  "Bloomberg",
  "Harvard Business Review ",
  "Finanzen",
  "Wall Street Online Denmark",
  "Minyanville: Finance ",
  "International Business Times (UK)",
  "The Street",
  "Knowledia")


# resources for medial professionals
att_news_medical <- c(
  "MedicalXpress",
  "Medscape",
  "MedPage Today",
  "Alzforum",
  "The Medical News",
  "Medical News Today",
  "Medical Health News",
  "Health Medicinet",
  "Health Reporter",
  "Physician's Briefing",
  "Pediatric News ",
  "Drugs.com",
  "Medindia",
  "Deutsches Ärzteblatt",
  "Healio.com",
  "Doc Wire News",
  "Doctors Lounge",
  "OncLive",
  "Health Canal",
  "2 Minute Medicine ",
  "PLoS Medicine",
  "AJMC",
  "ecancer",
  "Medical Daily",
  "CN-Healthcare",
  "Cancer Network",
  "Health Day ",
  "medwireNews",
  "The ASCO Post",
  "Stat News",
  "Pharmastar Italy",
  "Physician's Weekly",
  "Pourquoi Docteur ",
  "MyNeuroNews",
  "Fight Aging!",
  "Pharmacy Times",
  "TCTMD",
  "Everyday Health",
  "Medicinenet",
  "Clinical Advisor",
  "VBIO",
  "Renal & Urology News",
  "PharmiWeb",
  "Laboratory Equipment ",
  "Neurology Advisor ",
  "Centre for Disease Research and Policy",
  "HCP Live",
  "Arzte Zeitung ",
  "Pharmazeutische Zeitung",
  "Medisch Contact ",
  "Diagnostic and Interventional Cardiology",
  "nutraingredients.com",
  "Pharmaceutical Journal",
  "Endocrinology Advisor",
  "Cancer Therapy Advisor",
  "Thelimbic",
  "Cardiovascular Business",
  "Madrid ",
  "Infection Control Today",
  "PM 360",
  "Rheumatology Advisor",
  "WooDZog.com",
  "Oncology Nurse Advisor ",
  "Medportal"
)

# popular science
att_news_pop_sci <- c(
  "National Geographic",
  "Medium US",
  "Gizmodo",
  "Gizmodo Australia",
  "Discover Magazine",
  "Big Think",
  "Nature",
  "Popmech",
  "Smithsonian Magazine",
  "Arstechnica",
  "AskByGeeks",
  "redOrbit",
  "Healthline ",
  "Eat This, Not That!",
  "elementy.ru",
  "New Atlas",
  "wissenschaft.de",
  "COSMOS magazine",
  "Space.com",
  "Science World Report",
  "Psych Central",
  "R&D",
  "WebMD News",
  "Focus.it",
  "Illustreret Videnskab",
  "TMCnet.com",
  "Australasian Science",
  "Care2",
  "Psychology Today",
  "Interesting Engineering",
  "Muy Interesante",
  "Qrius",
  "EarthSky",
  "Galileonet",
  "Gizmodo UK",
  "Scientias ",
  "Reader's Digest",
  "Galileu",
  "Nutra Ingredients USA",
  "Earth",
  "Scientific American",
  "Popular Science",
  "The Science Times, United States",
  "Forskning.se",
  "Gizmodo India")

# general news aggregation portals - often intended for journalists
att_news_aggregator <- c(
  "Big News Network",
  "Alert Breaking News - US",
  "Benzinga",
  "PR Newswire",
  "Business Wire",
  "UPI.com",
  "EX BULLETIN",
  "NewsBeezer",
  "True Viral News",
  "Today Headline",
  "Pressfrom",
  "News Azi",
  "Verve times",
  "Biz Wire Express",
  "Spoke",
  "Noodls",
  "Inside Headline",
  "journalbreak.Com",
  "PressNewsAgency",
  "World Today News",
  "7th Space Family Portal",
  "awsforwp",
  "Futurity",
  "GlobeNewswire",
  "Rocket News",
  "Le Lézard",
  "Crwe World",
  "My droll",
  "PR Newswire UK",
  "Day To News.com",
  "Express Informer",
  " TechNewsBoy",
  "Tek Deeps",
  "World News Network",
  "Headlines & Global News",
  "PressReleasePoint",
  "Germanic.News")

# science news aggregation portals - often intended for journalists
att_news_sci_aggregator <- c(
  "EurekAlert!",
  "AlphaGalileo",
  "Jotup",
  "Paperity",
  "Tech Register",
  "Science Daily",
  "Informationsdienst Wissenschaft",
  "Phys.org"
)

# scientific news portals - mainly aimed at scientists
att_news_sci_portal <- c(
  "ScienMag",
  "Bioportfolio",
  "Newswise",
  "Technology Networks",
  "Science Alert",
  "Spektrum",
  "Biospace",
  "Nanowerk",
  "Science Newsline",
  "LabRoots",
  "Innovations Report",
  "Bioengineer.org",
  "Sciencenewsnet.in",
  "Technology.org",
  "Genomeweb",
  "The Scientist Magazine",
  "Nature Asia ",
  "New Scientist",
  "Bionity",
  "Space Daily",
  "Futura-Sciences",
  "Science News",
  "Iflscience",
  "USNews.com",
  "ChemistryViews",
  "Sci-News",
  "Science/AAAS",
  "Galaxy Concerns",
  "Jura Forum",
  "Sky Nightly ",
  "Mongabay",
  "Naked Science",
  "Today Topics ",
  "Sciences et Avenir",
  "Agencia SINC",
  "Le Scienze",
  "Azocleantech.com",
  "Carbon Brief",
  "The National Interest",
  "LiveScience",
  "Engineers Online ",
  "physicsworld.com",
  "Lab Manager ",
  "GEN",
  "Nature World News",
  "Scinexx",
  "American Physical Society - Physics ",
  "HAL Archives-Ouvertes",
  "Earth & Space Science News",
  "Ebiotrade",
  "Tech Xplore",
  "APA",
  "My Science",
  "Chemical & Engineering News",
  "BioTech Gate",
  "Cancer Cell International",
  "Canaltech",
  "The Free Library",
  "Green Report (Italy)",
  "The Lancet",
  "The University of New Orleans Public Radio ",
  "AZO Life Sciences",
  "pro-physik.de",
  "Environmental News Network",
  "forskning.no",
  "Scicasts",
  "e! Science News",
  "Globalresearch",
  "Azom.com",
  "SeedQuest",
  "NCYT - Noticias de la Ciencia y la Technologia",
  "Advanced Science News",
  "Azonano",
  "ThriveGlobal")

# general interest news outlets - national
att_news_general <- c(
  "Yahoo! News",
  "The Conversation",
  "MSN",
  "Foreign Affairs New Zealand",
  "Newsbreak",
  "Mirage News",
  "Yahoo!",
  "Daily Mail",
  "BBC News",
  "The Guardian",
  "Scitech Daily",
  "Swift Telecast",
  "Inverse",
  "New York Times",
  "Nouvelles du monde",
  "Times of India",
  "CNN News",
  "Nachrichten Welt",
  "Huffington Post",
  "Morning Star",
  "infosurhoy",
  "DNYUZ",
  "Vice",
  "The Epoch Times",
  "Devdiscourse",
  "The Independent",
  "Google News",
  "Washington Post",
  "El País",
  "Sign of the Times",
  "Digital Journal",
  "The Raw Story",
  "Long Room",
  "Newsweek",
  "Salon",
  "SPIEGEL ONLINE",
  "The Atlantic",
  "Breitbart News Network",
  "ABC.net.au",
  "Eurasia Review",
  "The Express",
  "Channel News Asia CNA",
  "Espanol.news",
  "Scroll India ",
  "Sydney Morning Herald",
  "de Volkskrant",
  "Paperblog",
  "The Evening Telegraph",
  "La Vanguardia",
  "Free Mail South Africa",
  "ANI News",
  "FOX News",
  "Vox.com",
  "Daily Magazine",
  "РИА Новости",
  "Wired.com",
  "Der Standard",
  "ORF.at",
  "The Hindustan Times",
  "The Wire",
  "CanIndia",
  "Die Welt",
  "Slate France",
  "Hareetz ",
  "newsmax.com",
  "RT Network",
  "TIME Magazine",
  "New Zealand Herald",
  "IOL",
  "Latest Nigerian News",
  "The Siasat Daily",
  "World News SBS",
  "Bustle",
  "CNET",
  "CBC",
  "Europa Press",
  "NBC News",
  "The Tribune",
  "South Africa Today",
  "Helsingin Sanomat",
  "NPR",
  "Heise",
  "Alternet",
  "TODAY",
  "The Hindu",
  "Le Monde",
  "Illuminati Press",
  "CTV News",
  "ABC.es",
  "Sputnik News",
  "AP News",
  "USA Today",
  "New York Post",
  "La Repubblica",
  "Firstpost",
  "The Telegraph (UK)",
  "The Hill",
  "Gazeta.ru",
  "Lenta.ru",
  "Fanpage",
  "De Morgen",
  "Der Tagesspiegel",
  "The Straits Times",
  "Yahoo! News India",
  "Frankfurter Allgemeine",
  "The Malay Mail Online",
  "Terra (Spain)",
  "AOL",
  "LaSexta",
  "AOL (UK)",
  "La Nueva España",
  "Publico",
  "Men's Health",
  "The Herald",
  "CBS News",
  "NU",
  "Top Santé",
  "ABC desevilla",
  "El Periodico - ES",
  "Wheels24",
  "Zee News (India)",
  "The Week (India)",
  "Free ",
  "Herald Sun",
  "PBS",
  "Women's Health",
  "Daily Maverick ",
  "Metro UK",
  "Neue Zürcher Zeitung (NZZ)",
  "Health24",
  "Sohu News",
  "Yle.fi",
  "NuevoPeriodico",
  "Newslanes",
  "Outlook India",
  "Quartz")

# general interest news outlets - local
att_news_general_local <- c(
  "Arizona Daily Star",
  "Dispatch-Argus",
  "Lincoln Journal Star",
  "Seattle Post-Intelligencer",
  "WFMZ-TV 69",
  "New Kerala",
  "St. Louis Post-Dispatch",
  "AllAfrica",
  "Idaho Press",
  "New Canaan Advertiser",
  "The Bismarck Tribune",
  "Today UK News",
  "Billings Gazette",
  "SFGate",
  "infobae",
  "San Antonio Express-News",
  "Dailyhunt",
  "Houston Chronicle",
  "Latestly",
  "The Darien Times",
  "Shelton Herald",
  "Hawaii News Now",
  "NBC12",
  "WALB",
  "Wave 3 News",
  "The Buffalo News",
  "The Print",
  "KAIT-TV",
  "Northwest Indiana Times",
  "Rapid City Journal",
  "ZAP",
  "14 News",
  "Independent Record",
  "WDAM - TV",
  "South Carolina News Now",
  "KLTV",
  "WSFA ",
  "Winona Daily News",
  "WLOX",
  "Beatrice Daily Sun",
  "Columbus Telegram",
  "tdn.com",
  "WTVM",
  "The Indian Express",
  "Stuff.co.nz",
  "The Southern Illinoisan",
  "FOCUS Online",
  "MPR",
  "Missoulian",
  "Western Australia Today",
  "goskagit.com",
  "KPLC 7 News",
  "Brisbane Times",
  "The Age",
  "WMBF News",
  "WFLX Fox 29",
  "KSLA News 12",
  "WBOC 16",
  "KRQE",
  "Fairfield Citizen",
  "WISTV",
  "2 News",
  "Bozeman Daily Chronicle",
  "WFMJ",
  "The Bellingham Herald",
  "Gazette-Times",
  "KCBD",
  "News Channel 10",
  "News Channel",
  "CBS8",
  "KTRE",
  "KULR 8",
  "KXLY ",
  "Kuam",
  "Lexington Herald Leader",
  "Sun Herald",
  "KHQ",
  "Fox 19",
  "WAND 17",
  "NewsOn6",
  "Star Tribune",
  "KOAMNewsNow.com",
  "Fox 8 WVUE",
  "The Charlotte Observer",
  "WTOL",
  "Belleville News-Democrat ",
  "News Tribune",
  "NewsWest9",
  "The Wichita Eagle",
  "ABC 7 News KSWO",
  "Deccan Chronicle",
  "KLKN-TV Eyewitness News",
  "News 9",
  "The Sentinel (Pennsylvania)",
  "Idaho Statements",
  "abc8news",
  "Raleigh News and Observer ",
  "Star-Telegram",
  "Cleveland 19",
  "Los Angeles Times",
  "News Channel 6",
  "CHANNEL 3000",
  "News Channel 11 wjhl.com",
  "Tri-City Herald",
  "Mississippi News Now ",
  "Ledger-Enquirer",
  "WMC Action News 5",
  "ABC27",
  "Your Basin",
  "The Telegraph (Georgia)",
  "WTOC",
  "Bakersfield",
  "The Island Packet",
  "Bradenton Herald",
  "KOIN 6",
  "WAFB 9",
  "The Canberra Times",
  "WGN9",
  "Wjtv.com",
  "The Olympian",
  "KPBS",
  "Informnny",
  "Myrtle Beach",
  "The Fresno Bee",
  "Philly.com",
  "WBOY",
  "KTEP El Paso",
  "Kansas City Star",
  "Everything Lubbock",
  "CIProud.com",
  "Count on News 2",
  "Centre Daily Times",
  "FOX31 Denver KDVR-TV",
  "KVIA",
  "48 WAFF",
  "WRCB- TV",
  "MyTwinTiers.com",
  "NBC Right Now KNDU 25",
  "Erie News Now",
  "KRWG TV/FM",
  "KTEN",
  "Tri States Public Radio",
  "WCBE ",
  "Iowa Public Radio",
  "Texomashomepage.com",
  "WFRV",
  "La Voz Digital",
  "YourErie.com",
  "WCAX",
  "KUNM",
  "Merced Sun-Star",
  "Fox 14 News",
  "Daijiworld.com",
  "Kxan",
  "TriStateHomepage.com",
  "Northern Public Radio",
  "azfamily.com",
  "KFVE The Home Team",
  "Weather herald",
  "Wlns.com",
  "Kansas Public Radio",
  "KX News",
  "Omaha Public Radio",
  "The Deccan Herald",
  "WVPE",
  "Arizona Public Radio",
  "Killeen Daily Herald",
  "News Channel 8 ",
  "Winnipeg Free Press",
  "KUSI News",
  "Witchita's Public Radio",
  "Boise State Public Radio",
  "Radio Acadie",
  "WECT News 6",
  "KEYC News 12",
  "WXPR",
  "WBTW News13",
  "WUNC",
  "Interlochen Public Radio",
  "KBTX-TV",
  "ABC 6 News WLNE",
  "MyHighPlains.com",
  "WPRI 12 Eyewitness News",
  "A Koahnic Broadcast Station",
  "Central Coast Public Radio",
  "Faro de Vigo",
  "KCRG.com",
  "WSAV3",
  "Wyoming Public Radio",
  "Georgia Public Radio",
  "The Modesto Bee",
  "WJCT",
  "Northeastern Indiana Public Radio ",
  "WVNS-TV",
  "The Daily Times",
  "WNCT9",
  "MyChamplainValley.com",
  "Irish Examiner",
  "KGET",
  "Myarklamiss.com",
  "North East Public Radio",
  "The Northern Echo",
  "FourStatesHomepage",
  "WTRF 7 News",
  "OZARKSFIRST.com",
  "WBRC",
  "Wales Online ",
  "Diario de Mallorca",
  "Fox News 26")
