national_news_nl <- c(
  "De Telegraaf",
  "De Telegraaf.nl",
  "Algemeen Dagblad",
  "AD/Algemeen Dagblad.nl",
  "AD/Algemeen Dagblad",
  "Metro",
  "Metro (NL)",
  "De Volkskrant",
  "De Volkskrant.nl",
  "de Volkskrant (Abstract) / MD Info",
  "de Volkskrant (Abstract) / MD Info",
  "De Telegraaf (Abstract) / MD Info",
  "NRC Handelsblad",
  "Trouw",
  "Trouw.nl",
  "Reformatorisch Dagblad",
  "Nederlands Dagblad",
  "NRC Next",
  "NRC",
  "NRC.NEXT",
  "NRC.nl",
  "WebNews - Dutch",
  "Metronieuws.nl",
  "Spits"
)

finance_news <- c(
  "Het Financieele Dagblad",
  "Het Financieele Dagblad (Abstract)/MD Info",
  "FD.nl",
  "Het Financieele Dagblad (Abstract)/MD Info",
  "AFR Online",
  "American Banking and Market News",
  "Australian Financial Review",
  "Briefing.com",
  "FEM Business",
  "Fem de Week",
  "Financial Buzz",
  "NRC Handelsblad (Abstract) / MD Info",
  "National Post (f/k/a The Financial Post) (Canada)",
  "QUOTE",
  "Quote",
  "Quotenet",
  "The Associated Press",
  "Business Wire"
)

aggregators <- c(
  "Africa News",
  "Agence France Presse -- English",
  "Associated Press State & Local",
  "Associated Press Financial Wire",
  "Canadian Press",
  "Canwest News Service",
  "Asian News International (ANI)",
  "Associated Press International",
  "Associated Press Online",
  "CountryWatch Reviews",
  "GlobeNewswire - EnglishGlobeNewswire - English",
  "Hindustan Times",
  "Impact Financial News",
  "Global English (Middle East and North Africa Financial Network)",
  "Global Round Up - ADRs and Depository Receipts",
  "Global Round Up - Bullish and Bearish Signals",
  "India Education Diary",
  "India Engineering news",
  "India Pharma News",
  "Indian Health care news",
  "Industry SnapShot",
  "MENAFN - Business & Finance News (English)",
  "MENAFN - Press Releases (English)",
  "Market News Publishing",
  "MarketLine NewsWire (Formerly Datamonitor)",
  "Marketwired",
  "PR Newswire US",
  "Pivotal Sources",
  "Plus Patent News",
  "Postmedia Breaking News",
  "Press Association",
  "Press Association Mediapoint",
  "TVEyes - BBC 1 Scotland",
  "TVEyes - BBC Radio 4",
  "TVEyes - BBC Radio 5 Live",
  "TVEyes - ITV 1 London",
  "Tenders Monitor Africa-Asia",
  "Tendersbiz",
  "The Associated Press State & Local Wire",
  "The Canadian Press (CP)",
  "The Canadian Press(CP)",
  "Thomson Reuters ONE",
  "Trends",
  "UPI",
  "US States News",
  "united Press International",
  "WebNews - Academic",
  "WebNews - English",
  "News Bites - Private Companies",
  "News Bites - People in Business",
  "News Bites - Benelux: Netherlands",
  "News Bites - Nordic: Denmark",
  "OzEquities News Bites (Australia)",
  "Australian Company News Bites - Stock Report",
  "News Bites - Western Europe: Spain",
  "News Bites - Western Europe : Germany",
  "News Bites - Western Europe",
  "News Bites - Western Europe: Switzerland",
  "News Bites - Nordic: Sweden",
  "Plus Company Updates(PCU)",
  "Targeted News Service", 
  "US Fed News",
  "States News Service",
  "US Official News",
  "PR Newswire", 
  "M2 PressWIRE", 
  "Premium Official News",
  "European Union News", 
  "TendersInfo", 
  "Impact News Service",
  "GlobeNewswire",
  "PR Newswire Europe",
  "PR.com",
  "ENP Newswire",
  "FinancialWire",
  "Mena Report",
  "Australian Government News",
  "London Stock Exchange Aggregated Regulatory News Service (ARNS)",
  "Congressional Documents and Publications",
  "FD (Fair Disclosure) Wire",
  "University Wire"
  )

local_int <- c(
  "Bangor Daily News (Maine)",
  "DAILY MAIL (London)",
  "Belfast Telegraph",
  "Belfast Telegraph Online",
  "Burger with Relish",
  "Canberra Times (Australia)",
  "Charleston Daily Mail (West Virginia)",
  "Charleston Gazette (West Virginia)",
  "Chicago Daily Herald",
  "Christian Science Monitor (Boston, MA)",
  "Dayton Daily News (Ohio)",
  "Deseret Morning News (Salt Lake City)",
  "Edmonton Journal (Alberta)",
  "Hamilton Spectator (Ontario, Canada)",
  "Manchester Evening News",
  "Ottawa Citizen",
  "Pittsburgh Post-Gazette (Pennsylvania)",
  "Racing Post",
  "Richmond Times Dispatch (Virginia)",
  "Right Vision News",
  "Spokesman Review (Spokane, WA)",
  "St. Louis Post-Dispatch (Missouri)",
  "St. Petersburg Times (Florida)",
  "Star Tribune (Minneapolis, MN)",
  "Sydney Morning Herald (Australia)",
  "Telegraph Herald (Dubuque, IA)",
  "The Age (Melbourne, Australia)",
  "The Atlanta Journal and Constitution",
  "The Atlanta Journal-Constitution",
  "The Bismarck Tribune",
  "The Calgary Herald (Alberta)",
  "The Gazette (Montreal)",
  "The Herald (Glasgow)",
  "The Leader-Post (Regina, Saskatchewan)",
  "The Philadelphia Inquirer",
  "The Press (Christchurch, New Zealand)",
  "The Record (Kitchener-Waterloo, Ontario)",
  "The Salt Lake Tribune",
  "The Tampa Tribune (Florida)",
  "The Vancouver Sun (British Columbia)",
  "Times Colonist (Victoria, British Columbia)",
  "Wisconsin State Journal (Madison, Wisconsin)",
  "thespec.com"
)

other_int <- c(
  "The Times of India (TOI)",
  "China Daily",
  "CE Noticias Financieras English",
  "Daily Mirror",
  "Daily Record",
  "De Morgen.be",
  "Eurasia Review",
  "Express Online",
  "Irish Independent",
  "South China Morning Post",
  "Thai News Service",
  "The Australian",
  "The Christian Science Monitor",
  "The Irish Times",
  "The New Zealand Herald",
  "The Star (South Africa)",
  "The Straits Times (Singapore)",
  "The Sun (England)",
  "mirror.co.uk"
)

regional_news_nl <- c(
  "Rijn en Gouwe",
  "De Dordtenaar",
  "De Gooi- en Eemlander.nl",
  "De Krant van West-Vlaanderen",
  "Dagblad Flevoland",
  "Almere Vandaag",
  "Alphen.cc",
  "De Limburger",
  "Gelderlander",
  "De Twentsche Courant Tubantia",
  "De Gelderlander",
  "De Gelderlander.nl",
  "Stentor",
  "Noordhollands Dagblad",
  "Dagblad van het Noorden",
  "Brabants Dagblad",
  "BN/DeStem",
  "BN De Stem.nl",
  "Tubantia",
  "Tubantia.nl",
  "Eindhovens Dagblad",
  "BN De Stem",
  "Leeuwarder Courant",
  "Het Parool",
  "Het Parool.nl",
  "Provinciale Zeeuwse Courant",
  "Haarlems Dagblad",
  "Leidsch Dagblad",
  "De Gooi- en Eemlander",
  "Nieuwsblad Noordoost-Friesland",
  "Steenwijker Courant",
  "Friesch Dagblad",
  "AD/Haagsche Courant",
  "AD/Rotterdams Dagblad",
  "AD/Utrechts Nieuwsblad",
  "Noordhollands Dagblad",
  "AD/Groene Hart",
  "AD/De Dordtenaar",
  "AD/Amersfoortse Courant",
  "AD/Rivierenland",
  "Limburgs Dagblad",
  "Brabants Dagblad.nl",
  "Eindhovens Dagblad.nl",
  "De Stentor.nl",
  "De Stentor",
  "De Stentor/Zwolse Courant",
  "De Stentor/Gelders Dagblad",
  "De Stentor/Zutphens Dagblad",
  "De Stentor/Nieuw Kamper Dagblad",
  "De Stentor/Dagblad Flevoland",
  "De Stentor/Veluws Dagblad",
  "De Stentor/Deventer Dagblad",
  "Dagblad Tubantia/Twentsche Courant",
  "de limburger.nl",
  "De Stentor/Apeldoornse Courant",
  "DAGBLAD VAN HET NOORDEN",
  "De Stentor/Sallands Dagblad",
  "De Stentor/ Deventer Dagblad",
  "De Stentor/Gelders Dagblad",
  "De Stentor/Zutphens Dagblad",
  "De Stentor/Zwolse Courant",
  "De Groene Amsterdammer",
  "De Stentor/Apeldoornse Courant",
  "De Stentor/Dagblad Flevoland",
  "Dagblad van het Noorden.nl",
  "Noordhollands Dagblad.nl",
  "De Stentor/Deventer Dagblad",
  "Rotterdams Dagblad",
  "Friesch Dagblad",
  "Haarlems Dagblad.nl",
  "Meppeler Courant",
  "IJmuider Courant.nl",
  "Dagblad voor Zuidwest-Nederland",
  "Zwolse Courant",
  "Ijmuider Courant",
  "Leidsch Dagblad.nl",
  "Utrechts Nieuwsblad",
  "Haagsche Courant",
  "Leeuwarder Courant.nl",
  "De Stentor/Nieuw Kamper Dagblad",
  "Amersfoortse Courant",
  "Goudsche Courant",
  "Friesch Dagblad.nl",
  "Dagblad Rivierenland",
  "PZC.nl",
  "Woerdense Courant",
  "Goudse post",
  "Tubantia.nl",
  "nu.nl",
  "Voorburgse Courant",
  "De Stad Wageningen",
  "De Stem",
  "Knack Magazine",
  "IJmuider Courant",
  "De Brug Nijmegen")

professional_pub <- c(
  "De Accountant",
  "Accountant",
  "Cobouw",
  "Contify Life Science News",
  "Boerderij",
  "Logistiek",
  "Psychologie Magazine",
  "Boerderij Vandaag",
  "Nieuwsblad Transport",
  "Vrij Nederland",
  "Food & Agri business",
  "Pakblad",
  "Nieuwsblad Transport",
  "restaurantonline.co.uk",
  "Groenten en Fruit",
  "Pluimveehouderij",
  "Logistiek Krant",
  "Nieuwe Oogst",
  "Opzij"
  )

science_pub <- c(
  "Elsevier",
  "Elsevier Weekblad",
  "Journal Of Marketing",
  "Journal of Marketing Research",
  "Medical Xpress",
  "New Scientist",
  "Pharma & Healthcare Monitor Worldwide",
  "Phys.org - Science and Technology News",
  "Space Daily",
  "The Chronicle of Higher Education"
)

high_profile_int <- c(
  "The Times Higher Education Supplement",
  "Financial Times (London, England)",
  "The New York Times", 
  "The Times (London)",
  "MailOnline",
  "Guardian.com",
  "The Guardian - Final Edition",
  "Guardian Weekly",
  "FT.com",
  "FT.com Headlines",
  "The Toronto Star",
  "thetimes.co.uk",
  "Xinhua General News Service",
  "The Guardian (London)",
  "The International Herald Tribune",
  "The Guardian",
  "CNN Wire",
  "telegraph.co.uk",
  "The Daily Telegraph (London)",
  "The Independent (United Kingdom)",
  "The Independent (London)",
  "The Guardian(London)",
  "Independent.co.uk",
  "CNN.com",
  "The Sunday Times (London)",
  "NEW YORK TIMES",
  "The New York Times - International Edition",
  "The Times",
  "USA TODAY")
